### ISSUE TITLE
Improve folder structure

### ISSUE THREAD

**Issue by heyimjonas** [stas00/ml-engineering#15]
Would it be possible to improve the folder structure so it somewhat matches your table of contents?

eg: 
├── Part 1
│   ├── Topic 1
│   ├── Topic 2
├── Part 2
│   ├── Topic 3
│   ├── Topic 4

**Comment by stas00** [comment]
It's a good suggestion, Jonas and I agree that this would be nice. 

The structure is still emerging and changes every month or so, e.g. I'm not sure if each component should have its own performance and debug sub-section, or whether it's better to have them inverted.

Unfortunately, most of the time github doesn't redirect when files are moved and provides no equivalent of `.htaccess` files to let users manage it, so I don't want to have too many broken links at this stage and using a flat structure.

Eventually it will be awesome and intuitive and easy to navigate.

**Comment by heyimjonas** [comment]
Yeah that is reasonable, rewriting all the links etc. every month is not really worth it if it's gonna change again

Hope you'll keep it in mind for when it's more finalized :) 

I'll patiently wait and read your content till then.

**Comment by stas00** [comment]
I finally had the time to do a massive re-org in https://github.com/stas00/ml-engineering/pull/25

Hopefully it's much easier to read now.

And of course I will continue improving the layout.
