### ISSUE TITLE
pip install -r build/requirements.txt fails due to github_md_utils

### ISSUE THREAD

**Issue by ebowman** [stas00/ml-engineering#20]
`ERROR: Could not find a version that satisfies the requirement github_md_utils (from versions: none)
ERROR: No matching distribution found for github_md_utils
`

Any ideas? Googling github_md_utils gives 0 hits: https://www.google.com/search?client=safari&rls=en&q=github_md_utils&ie=UTF-8&oe=UTF-8

Thanks!

**Comment by sebastiancadena** [comment]
+1

**Comment by ebowman** [comment]
Thanks!
