### ISSUE TITLE
Quarto Site

### ISSUE THREAD

**Issue by saforem2** [stas00/ml-engineering#28]
Hey @stas00 ,

I added a [comment on my previous PR](https://github.com/stas00/ml-engineering/pull/17#discussion_r1496916638):

> @stas00 if you're curious, I've done some re-org and tried rendering everything with Quarto in [my fork](https://github.com/saforem2/ml-engineering)
>
> You can see it online at:
> 
> https://saforem2.github.io/ml-engineering/
> 
> This is mostly just a first (rough) pass (and copied + modified from existing Quarto sites I've made),
> but I made an effort to fix / change things where appropriate (e.g. links, etc.)
> 
> disclaimer: I mostly just did this out of personal curiosity / testing, but thought I'd share incase you're interested 🤷🏻‍♂️

I know that _I, personally_ have a hard time keeping track of GitHub comments ( especially on closed PRs 😂 ),  
so I figured it probably made more sense to move the discussion to a separate issue (I hope that's okay)

**Comment by stas00** [comment]
Hi Sam, 

Sorry, I'm not quite following you here. Why are you doing this work?

Is something wrong with the current repo?

**Comment by saforem2** [comment]
> Sorry, I'm not quite following you here. Why are you doing this work?

Honestly I just wanted to

- see / test some automation scripts for converting (+ formatting) `**/*.md` to `**/*.qmd` that I've been working on
- test Quarto on a larger (book-like) site with multiple pages and look at some of the organizational aspects for a larger project

and this seemed like a good fit 🤷🏻‍♂️

> Is something wrong with the current repo?

no not at all!

to be honest I initially planned to just play with it locally and keep it to myself, 
but figured I'd push the changes back to my fork before scrapping it

**Comment by stas00** [comment]
Thank you for clarifying, Sam. 

As I mentioned in the other thread I actually prefer to have it done in 2 stages with intermediary html because then I have far more control over the output and can deploy existing tools that work with html - e.g. I check links using `linkchecker` and I'm very familiar with as I have been using it for year.
