### ISSUE TITLE
TPU v4 has 1,200GB/s of mem bandwidth and not 2,400, right?

### ISSUE THREAD

**Issue by rodrigo-f-nogueira** [stas00/ml-engineering#40]
In the README.md:
<img width="501" alt="Screen Shot 2024-04-07 at 9 25 37 PM" src="https://github.com/stas00/ml-engineering/assets/121117945/0e071038-cfe1-4ea3-8116-de3ba09875cd">

On Google's documentation: https://cloud.google.com/tpu/docs/v4

<img width="818" alt="Screen Shot 2024-04-07 at 9 27 05 PM" src="https://github.com/stas00/ml-engineering/assets/121117945/966028a6-be24-4adc-9e63-eba0b98f4367">

**Comment by stas00** [comment]
Thanks a lot, @rodrigo-f-nogueira for reporting my mistake and the correct value.
https://github.com/stas00/ml-engineering/pull/43 fixed it.
