### ISSUE TITLE
Question about the right hidden dim when using SwiGLU

### ISSUE THREAD

**Issue by Thytu** [stas00/ml-engineering#45]
### Context

In the [SwiGLU-based MLP](https://github.com/stas00/ml-engineering/tree/3bd6a4c9f5c5a98fb4092ebf03ab01b779b0893e/training/performance#swiglu-based-mlp) section, it is stated :

> The SwiGLU-based MLP contains an additional learned matrix in its activation function. There the MLP block contains 3 matrices instead of the original 2. To preserve the total number of parameters in the MLP block the paper that introduces [SwiGLU](https://arxiv.org/abs/2002.05202) proposes to use dim_mlp = 4*dim_attninstead of the typical dim_mlp = 8/3*dim_attn. The [The Case for Co-Designing Model Architectures with Hardware](https://arxiv.org/abs/2401.14489) paper provides recommendations for finding the value of hidden dimension (h) that would lead to the best matmul performance, and if you used 8/3*h is likely to result in a much slower MLP block, because 1/3 will break all the alignments.

And later on, in the [final recommendations for model sizing](https://github.com/stas00/ml-engineering/tree/3bd6a4c9f5c5a98fb4092ebf03ab01b779b0893e/training/performance#final-recommendations-for-model-sizing) section:

> The full recommendations are:
> [...]
> 6. For SwiGLU search for the best performing hidden size close to 8/3*h
 
It took me a couple of readings to understand those statements, and I'm still not entirely certain of their meaning tbh.
It could just be me, as I'm learning all those informations but I do have a few questions about it:

#### Right hidden dim when using SwiGLU 
[Here](https://github.com/stas00/ml-engineering/tree/3bd6a4c9f5c5a98fb4092ebf03ab01b779b0893e/training/performance#final-recommendations-for-model-sizing) you said that: "_For SwiGLU search for the best performing hidden size close to `8/3*h`_"

But earlier you've written "_if you used `8/3*h` is likely to result in a much slower MLP block, because 1/3 will break all the alignments_".

Does that mean that you still recommend using `8/3*h` despite it leading to slower MLP block?

#### 1/3 breaking the alignments
Also regarding the statement "_and if you used `8/3*h` is likely to result in a much slower MLP block, because 1/3 will break all the alignments._"
I'm not sure what the $1/3$ refers to, clarify its meaning for me?

----
Note: It could greatly help newcomers like myself to have those small sections clarified for better understanding :)

**Comment by stas00** [comment]
@Thytu, please correct me if I'm wrong but I'm seeing you highlighting 2 independent things:

1. 8/3 vs 1/3
2. 8/3*h vs close to 8/3*h

correct?

1. The first one is easy, I was trying to say that it's the dividing by 3 that messes up the best shape, multiplying by 8 is unlikely to cause a big degradation in performance. So I probably should stick to saying that it's 8/3 instead of 1/3 - what that make things clear?

2. continue saying a close to 8/3*h, and the exact number should be measured using the provided script.

Let me draft a PR for you to review and then we can sort it out and then merge an improved version.

**Comment by stas00** [comment]
Please have a look at the proposed https://github.com/stas00/ml-engineering/pull/46 and please make further suggestions if something is still unclear. Thank you.

**Comment by Thytu** [comment]
(Continuing the discussion on #46)
