### ISSUE TITLE
slurm job array change nodes

### ISSUE THREAD

**Issue by ethanhe42** [stas00/ml-engineering#61]
> The only limitation of this recipe is that you can't change the number of nodes, time and hardware and partition constraints once the job array was launched.

the number of nodes can be changed by `scontrol update jobid=123 numnodes=8` as long as the job is pending.

https://github.com/stas00/ml-engineering/blob/master/orchestration/slurm/users.md

**Comment by stas00** [comment]
that's true - would you like to make a PR to add this note so that your contribution is registered, @ethanhe42? It's up to you of course, I can add it if you don't want to be bothered.

Thank you.
