### ISSUE TITLE
GPU utilization monitoring

### ISSUE THREAD

**Issue by fortminors** [stas00/ml-engineering#72]
Thank you for sharing the MLE Open Book with the community, its really useful.
I tried to follow your guide on getting GPU utilization rates [here](https://github.com/stas00/ml-engineering/blob/master/compute/accelerator/nvidia/debug.md#how-to-get-the-real-gpu-utilization-metrics) to find out that the dcgm-exporter only works for datacenter GPUs V10x/A10x/H10x (as per [this](https://github.com/NVIDIA/dcgm-exporter/issues/22#issuecomment-2116538739) comment), but I only have consumer level GPUs (GTX 30xx/40xx).
It would be awesome if you could add that disclaimer.
 
However, what makes me curious is whether you know any tools (except profilers like nsys and ncu) that would allow me getting SM occupancy and other GPU utilization metrics in realtime without interfering the main program, so working by the side?

**Comment by stas00** [comment]
Thank you for the suggestion, Georgy, pushed it here https://github.com/stas00/ml-engineering/commit/2bf9b8077d475e63636047a0b9b667f58ba8d575

I don't know, let's ask https://x.com/StasBekman/status/1844173167713251498

**Comment by fortminors** [comment]
nvidia-smi uses nvml internally, and the latter supports SM and other [GPM metrics](https://docs.nvidia.com/deploy/nvml-api/group__nvmlGpmEnums.html#group__nvmlGpmEnums) which are not shown by nvidia-smi by default. However, the [nvml documentation](https://docs.nvidia.com/deploy/nvml-api/nvml-api-reference.html#nvml-api-reference) states that the NVIDIA GeForce Line has only Limited Support.

There are [python bindings](https://pypi.org/project/nvidia-ml-py/) to nvml, so I made a little script below that would show the metrics if the device is supported. I haven't tested it fully, as it's not supported on my GPU. 
Hopefully, somebody finds it useful, as there are not many samples available for nvml.

```python
# Script dependencies
# /// script
# dependencies = [
#   "nvidia-ml-py==12.560.30",
# ]
# ///

import pynvml

pynvml.nvmlInit()

metrics_to_monitor = [pynvml.NVML_GPM_METRIC_SM_UTIL, pynvml.NVML_GPM_METRIC_SM_OCCUPANCY]

device_count = pynvml.nvmlDeviceGetCount()
for device_idx in range(device_count):
    device_handle = pynvml.nvmlDeviceGetHandleByIndex(device_idx)
    device_name = pynvml.nvmlDeviceGetName(device_handle)
    supported = pynvml.nvmlGpmQueryDeviceSupport(device_handle).isSupportedDevice != 0

    if not supported:
        print(f"Device {device_idx}: {device_name} does not support GPM metrics")
        continue
    print(f"Monitoring GPM metrics for device {device_idx}: {device_name}")
    
    sample1 = pynvml.nvmlGpmSampleGet(device_handle, pynvml.nvmlGpmSampleAlloc())
    sample2 = pynvml.nvmlGpmSampleGet(device_handle, pynvml.nvmlGpmSampleAlloc())

    metrics_get = pynvml.c_nvmlGpmMetricsGet_t()
    metrics_get.version = pynvml.NVML_GPM_METRICS_GET_VERSION
    metrics_get.numMetrics = len(metrics_to_monitor)
    metrics_get.sample1 = sample1
    metrics_get.sample2 = sample2

    for i, metric in enumerate(metrics_to_monitor):
        metrics_get.metrics[i].metricId = metric

    pynvml.nvmlGpmMetricsGet(metrics_get)

    for i, metric in enumerate(metrics_to_monitor):
        metric_result = metrics_get.metrics[i]
        metric_name = str(metric_result.metricInfo.longName, encoding='utf-8')
        if metric_result.nvmlReturn != 0:
            print(f"Error: got nonzero nvmlReturn for metric {metric_name}")
        else:
            print(f"Metric {metric_name}: {metric_result.value}")

    pynvml.nvmlGpmSampleFree(sample1)
    pynvml.nvmlGpmSampleFree(sample2)

pynvml.nvmlShutdown()
```

**Comment by stas00** [comment]
indeed, `pynvml` gives you access to everything `nvidia-smi` does, but programmatically - it's very neat

I have been using it in https://github.com/stas00/ipyexperiments, e.g. to get the real memory usage of the card and not the one reported by torch: https://github.com/stas00/ipyexperiments/blob/569a450e204b1da60e5ef07a96c91553b286ea14/ipyexperiments/utils/mem.py#L63-L65

I also used it to get wattage stats.

**Comment by stonelazy** [comment]
> indeed, `pynvml` gives you access to everything `nvidia-smi` does, but programmatically - it's very neat 
> I also used it to get wattage stats.

For our simple monitoring app, I've been using [gpustat](https://github.com/wookayin/gpustat), which is a higher-level wrapper around `nvidia-ml-py` (this is the official NVML bindings and NOT `pynvml`). It offers easy access to key GPU stats like memory, temperature, and wattage. I’m not entirely sure if it exposes all the lower-level APIs from `pynvml` or `nvidia-ml-py`, but it’s been working well for my needs so far.

**Comment by stas00** [comment]
Thank you for sharing how you approach this, @stonelazy.

**Comment by stas00** [comment]
as there is no more activity here, closing this for now. Please feel free to re-open if more discussion is needed.

**Comment by zlH518** [comment]
> Thank you for sharing the MLE Open Book with the community, its really useful.感谢您与社区分享《机器学习工程开放书籍》，它真的非常有用。 I tried to follow your guide on getting GPU utilization rates [here](https://github.com/stas00/ml-engineering/blob/master/compute/accelerator/nvidia/debug.md#how-to-get-the-real-gpu-utilization-metrics) to find out that the dcgm-exporter only works for datacenter GPUs V10x/A10x/H10x (as per [this](https://github.com/NVIDIA/dcgm-exporter/issues/22#issuecomment-2116538739) comment), but I only have consumer level GPUs (GTX 30xx/40xx).我试图遵循您关于获取 GPU 利用率指南的说明，但发现 dcgm-exporter 仅适用于数据中心 GPU V10x/A10x/H10x（如该评论所述），但我只有消费级 GPU（GTX 30xx/40xx）。 It would be awesome if you could add that disclaimer.如果您能添加这个免责声明那就太棒了。
> 
> However, what makes me curious is whether you know any tools (except profilers like nsys and ncu) that would allow me getting SM occupancy and other GPU utilization metrics in realtime without interfering the main program, so working by the side?然而，让我好奇的是，您是否知道除了性能分析器如 nsys 和 ncu 之外，还有哪些工具可以实时获取 SM 占用和其他 GPU 利用率指标，而不会干扰主程序，可以并行工作？


It seems that using dcgm-exporter to monitor consumer GPUs is feasible, as I used it to monitor my three 4090s last week.

**Comment by fortminors** [comment]
@zlH518 How did you manage to do that?
