### ISSUE TITLE
How can operations with the INT8 data type be performed using a GPU accelerator card? Is dequantization required?

### ISSUE THREAD

**Issue by cpollo55** [stas00/ml-engineering#75]

**Comment by stas00** [comment]
General ML questions belong to various other forums. SO is probably a good place to start, e.g, try: https://stackoverflow.com/questions/74674753/how-does-int8-inference-really-works

**Comment by cpollo55** [comment]
What I mean is, how do you evaluate the INT8 data type in the benchmarks you publish?

**Comment by stas00** [comment]
Which benchmark? You're not giving me context to be able to answer your question

**Comment by cpollo55** [comment]
sorry,here is:
https://github.com/stas00/ml-engineering/tree/master/compute/accelerator/benchmarks

| Data type \ TFLOPS     | w/o Sparsity | w/ Sparsity |
| :--------------------  | -----------: | ----------: |
| FP32                   |         19.5 |         n/a |
| Tensor Float 32 (TF32) |          156 |         312 |
| BFLOAT16 Tensor Core   |          312 |         624 |
| FP16 Tensor Core       |          312 |         624 |
| FP8 Tensor Core        |          624 |        1248 |
| INT8 Tensor Core       |          624 |        1248 |

Notes:

**### * INT8 is measured in TeraOperations as it's not a floating operation.**

**Comment by stas00** [comment]
The table you shared has nothing to do with the benchmarks you linked to.

It comes from https://github.com/stas00/ml-engineering/tree/master/compute/accelerator#tflops and if you read closely it says:

> For example, here are a few entries from the theoretical peak TFLOPS from [A100 spec](https://www.nvidia.com/en-us/data-center/a100/):

So if you want to work with int8 tensors it'll use those int8 tensor cores to do the computation.

Some of the quantization techniques use int8 tensors and yes, they would typically dequantize those numbers back to a floating type before doing the math. 

Did this resolve your query?
