### ISSUE TITLE
AMD MI250X MAMF efficiency is wrong

### ISSUE THREAD

**Issue by rlrs** [stas00/ml-engineering#76]
The MAMF is measured on a single GCD, while the 383 TFLOPs as specified is for 2 GCDs.
I'm also unable to achieve 147 TFLOPs on a single GCD however, I find that it peaks at 127, but I attribute that to setup differences.

**Comment by stas00** [comment]
That's an excellent heads up, @rlrs 

I have no access to MI250X - let me check with the person who sent me that info:
https://github.com/stas00/ml-engineering/commit/359ee1ce535fd8b2ffaa8060199319ee0eb953f2

**Comment by Eliovp** [comment]
Indeed! You're right @rlrs !
I did the performance on one of our MI250x systems.
Great catch, I should have mentioned this as well :)

**Comment by stas00** [comment]
Thank you, @rlrs and @Eliovp

Fixed in: https://github.com/stas00/ml-engineering/commit/37d41a743bf4ff526f3c9153a414ca62995a605c
